//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageCropResize.WinCore.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageCropResize.WinCore.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted Image.
        /// </summary>
        public static string ConvertedImageLabelText {
            get {
                return ResourceManager.GetString("ConvertedImageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard does not contain image..
        /// </summary>
        public static string NotAnImage_Message {
            get {
                return ResourceManager.GetString("NotAnImage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert: No saved values set for this preset..
        /// </summary>
        public static string NoValuesSet_Message {
            get {
                return ResourceManager.GetString("NoValuesSet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Image: {0}W x {1}H.
        /// </summary>
        public static string OriginalImageLabelText {
            get {
                return ResourceManager.GetString("OriginalImageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropped: {0}w x {1}h.
        /// </summary>
        public static string OutputCropped {
            get {
                return ResourceManager.GetString("OutputCropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resized: {0}w x {1}h.
        /// </summary>
        public static string OutputResized {
            get {
                return ResourceManager.GetString("OutputResized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}x, {1}y.
        /// </summary>
        public static string OutputXY {
            get {
                return ResourceManager.GetString("OutputXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image ready to convert! Select a preset button..
        /// </summary>
        public static string ReadyToConvert_Message {
            get {
                return ResourceManager.GetString("ReadyToConvert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin, click New Settings and save preset settings..
        /// </summary>
        public static string SaveNewPresets_Message {
            get {
                return ResourceManager.GetString("SaveNewPresets_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in desired settings below.\nThen click a preset button on the right to save the values..
        /// </summary>
        public static string SettingHowTo {
            get {
                return ResourceManager.GetString("SettingHowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image sucessfully converted and copied to clipboard..
        /// </summary>
        public static string Success_Message {
            get {
                return ResourceManager.GetString("Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to crop image, image is smaller than crop settings..
        /// </summary>
        public static string UnableToConvert_Message {
            get {
                return ResourceManager.GetString("UnableToConvert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Convert the image!.
        /// </summary>
        public static string UnableToConvertTheImage_Message {
            get {
                return ResourceManager.GetString("UnableToConvertTheImage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original image copied to clipboard, select preset button..
        /// </summary>
        public static string Undo_Message {
            get {
                return ResourceManager.GetString("Undo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin, copy image the image you&apos;d like to convert into clipboard..
        /// </summary>
        public static string WaitingForClipboardImage_Message {
            get {
                return ResourceManager.GetString("WaitingForClipboardImage_Message", resourceCulture);
            }
        }
    }
}
